//#define GxEPD2_DISPLAY_CLASS GxEPD2_4G_4G
#define GxEPD2_DISPLAY_CLASS GxEPD2_4G_BW

#define GxEPD2_DRIVER_CLASS GxEPD2_420_GDEY042T81

#define GxEPD2_4G_BW_IS_GxEPD2_4G_BW true
#define GxEPD2_4G_4G_IS_GxEPD2_4G_4G true
#define IS_GxEPD(c, x) (c##x)
#define IS_GxEPD2_4G_BW(x) IS_GxEPD(GxEPD2_4G_BW_IS_, x)
#define IS_GxEPD2_4G_4G(x) IS_GxEPD(GxEPD2_4G_4G_IS_, x)


#define MAX_DISPLAY_BUFFER_SIZE 65536ul // e.g.
#define MAX_HEIGHT(EPD) (EPD::HEIGHT <= MAX_DISPLAY_BUFFER_SIZE / (EPD::WIDTH / 4) ? EPD::HEIGHT : MAX_DISPLAY_BUFFER_SIZE / (EPD::WIDTH / 4))


GxEPD2_DISPLAY_CLASS<GxEPD2_DRIVER_CLASS, MAX_HEIGHT(GxEPD2_DRIVER_CLASS)> display(GxEPD2_DRIVER_CLASS(EPD_CS, EPD_DC, EPD_RST, EPD_BUSY));


#undef MAX_DISPLAY_BUFFER_SIZE
#undef MAX_HEIGHT